apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  selector:
    matchLabels:
      type: backend
  replicas: 2
  strategy:
    type: RollingUpdate       # 무중단 배포 방식
  minReadySeconds: 10
  template:
    metadata:
      labels:
        type: backend
    spec:
      containers:
        - name: backend-container
          image: beomiya/final_backend:1.VERSION
          readinessProbe:
            httpGet:
              path: /test/connect
              port: 6060
            initialDelaySeconds: 5    # 최초 Probe전의 지연 시간
            periodSeconds: 2          # Probe를 체크하는 시간 간격
            successThreshold: 3       # 성공 결과 수신 횟수
          ports:
            - containerPort: 6060
      terminationGracePeriodSeconds: 10   # 컨테이너가 강제 종료되기 전의 유예시간