version: '3'
services:
  db:
    image: mariadb:latest
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    environment:
        MARIADB_ROOT_PASSWORD: qwer1234
        MARIADB_DATABASE: masuri
        TZ: Asia/Seoul