apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontendStore-deployment
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  minReadySeconds: 10
  selector:
    matchLabels:
      resource: memory2
  template:
    metadata:
      labels:
        resource: memory2
    spec:
      containers:
        - name: frontendStore-container
          image: beomiya/final_store_frontend:1.VERSION
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5    # 최초 Probe전의 지연 시간
            periodSeconds: 2          # Probe를 체크하는 시간 간격
            successThreshold: 3       # 성공 결과 수신 횟수
          ports:
              - containerPort: 80
      terminationGracePeriodSeconds: 5