apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  minReadySeconds: 10
  selector:
    matchLabels:
      resource: memory3
  template:
    metadata:
      labels:
        resource: memory3
    spec:
      containers:
        - name: backend-container
          image: beomiya/final_backend:1.VERSION
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: 1Gi
            limits:
              memory: 2Gi
          envFrom:
            - configMapRef:
                name: back-config
      terminationGracePeriodSeconds: 5