
imp:
  imp_key: ${IMP_KEY}
  imp_secret: ${IMP_SECRET}

jwt:
  secret-key: ${SECRET_KEY}
  token:
    expired-time-ms: ${TOKEN_EXPIRED}

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}

  jpa:
    database-platform: ${JPA_DB}
    hibernate:
      ddl-auto: ${JPA_DDL}
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MariaDB102Dialect

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  redis:
    host: ${REDIS_MASTER}
    port: ${REDIS_PORT}



logging:
  level:
    org.springframework.security: DEBUG